use the current venv to launch therock build
- use the currently used python venv to launch
  the therock build from the rockbuilder_cfg.py
- This ensures that rockbuilder_cfg has all the
  python packages installed that the
  init_rcb_env.sh/bat installs.
- This fixes a following error detetected on windows
  where the build tried to use different python env
  which did not have the windows-curses installed.

Traceback (most recent call last):
  File "c:\rock\rockbuilder\rockbuilder.py", line 11, in <module>
    import rockbuilder_cfg as rcb_cfg_writer
  File "c:\rock\rockbuilder\rockbuilder_cfg.py", line 7, in <module>
    import curses
  File "C:\Python313\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

Signed-off-by: Mika Laitio <mika.laitio@amd.com>