therock stinkytofu gcc 16/fedora 44 uint32_t fix
Stinkytofu broke the hibBLASLt build on fedora/gcc 16
due to missing definitions because c++ headers shipped
with newer gcc versions have more fine detailed control
for include files to be included.

Fixes following type of errors by including
ctdint.h or cstdint and climits when needed:

  error: unknown type name 'uint32_t'
and
  error: use of undeclared identifier 'UINT_MAX'

Signed-off-by: Mika Laitio <mika.laitio@amd.com>