rocm sdk home linux fix for triton build
Triton 3.5 fails to detect the llvm and mlir
even on linux which have symlinks from
__rocm_sdk_devel directory to __rocm_sdk_core.

Fix is to set rocm_sdk_home always to
_rocm_sdk_core when python wheels are used.

Fixes a following error:
CMake Error at CMakeLists.txt:105 (find_package):
  Found package configuration file:

    /home/lamikr/.triton/llvm/llvm-7d5de303-ubuntu-x64/lib/cmake/mlir/MLIRConfig.cmake

  but it set MLIR_FOUND to FALSE so package "MLIR" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  LLVMNVPTXCodeGen LLVMNVPTXDesc LLVMNVPTXInfo

..
  File "/rcb_gfx90a_vllm/src_apps/triton_pytorch_29/setup.py", line 418, in run
    self.build_extension(ext)
  File "/rcb_gfx90a_vllm/src_apps/triton_pytorch_29/setup.py", line 526, in build_extension
    subprocess.check_call(["cmake", self.base_dir] + cmake_args, cwd=cmake_dir, env=env)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/rcb_gfx90a_vllm/src_apps/triton_pytorch_29', '-G', 'Ninja', '-DCMAKE_MAKE_PROGRAM=/rcb_gfx90a_vllm/.venv/bin/ninja', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DLLVM_ENABLE_WERROR=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/rcb_gfx90a_vllm/src_apps/triton_pytorch_29/build/lib.linux-x86_64-cpython-312/triton/_C', '-DTRITON_BUILD_PYTHON_MODULE=ON', '-DPython3_EXECUTABLE:FILEPATH=/rcb_gfx90a_vllm/.venv/bin/python', '-DPython3_INCLUDE_DIR=/usr/include/python3.12', '-DTRITON_CODEGEN_BACKENDS=nvidia;amd', '-DTRITON_PLUGIN_DIRS=', '-DTRITON_WHEEL_DIR=/rcb_gfx90a_vllm/src_apps/triton_pytorch_29/build/lib.linux-x86_64-cpython-312/triton', '-DLLVM_EXTERNAL_LIT=/rcb_gfx90a_vllm/.venv/bin/lit', '-DLLVM_INCLUDE_DIRS=/home/lamikr/.triton/llvm/llvm-7d5de303-ubuntu-x64/include', '-DLLVM_LIBRARY_DIR=/home/lamikr/.triton/llvm/llvm-7d5de303-ubuntu-x64/lib', '-DLLVM_SYSPATH=/home/lamikr/.triton/llvm/llvm-7d5de303-ubuntu-x64', "-Dpybind11_INCLUDE_DIR='/rcb_gfx90a_vllm/.venv/lib/python3.12/site-packages/pybind11/include'", "-Dpybind11_DIR='/rcb_gfx90a_vllm/.venv/lib/python3.12/site-packages/pybind11/share/cmake/pybind11'", '-DCMAKE_BUILD_TYPE=TritonRelBuildWithAsserts', '-DCMAKE_C_COMPILER=clang', '-DCMAKE_CXX_COMPILER=clang++', '-DCMAKE_LINKER=lld', '-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld', '-DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld', '-DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld', '-DJSON_INCLUDE_DIR=/home/lamikr/.triton/json//include', '-DJSON_SYSPATH=/home/lamikr/.triton/json/', "-Dpybind11_INCLUDE_DIR='/rcb_gfx90a_vllm/.venv/lib/python3.12/site-packages/pybind11/include'", "-Dpybind11_DIR='/rcb_gfx90a_vllm/.venv/lib/python3.12/site-packages/pybind11/share/cmake/pybind11'", '-DCUPTI_INCLUDE_DIR=/rcb_gfx90a_vllm/src_apps/triton_pytorch_29/third_party/nvidia/backend/include', '-DROCTRACER_INCLUDE_DIR=/rcb_gfx90a_vllm/src_apps/triton_pytorch_29/third_party/amd/backend/include']' returned non-zero exit status 1.
Operation failed

Signed-off-by: Mika Laitio <mika.laitio@amd.com>